services:
  mysql:
    image: mysql:8.4
    container_name: fintrack_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fintrack
      MYSQL_USER: fintrack_user
      MYSQL_PASSWORD: fintrack_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: